MAX_QUBITS_HINT: str
CIRCUIT_REWRITE_TRACES: str
UNITARY_FLAGS: str
PYTKET_INPUT_PARAMETERS: str
PYTKET_OP_GROUP: str
PYTKET_BIT_REGISTER_NAMES: str
PYTKET_QUBIT_REGISTER_NAMES: str
PYTKET_PHASE_EXPR: str
