blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/Quantinuum/tket2/discussions
    about: Ask questions and discuss ideas with the community
  - name: "🦀 Rust library documentation"
    url: https://docs.rs/tket
    about: Read the API documentation for the Rust library
  - name: "🐍 Python library documentation"
    url: https://quantinuum.github.io/tket2/
    about: Read the API documentation for the Python library
