name: Python wheels 🐍 (qis-compiler)

on:
  push:
    branches:
      - main
    tags:
      - "qis-compiler-v*"
  pull_request:
    # check builds work if qis-compiler build config changes
    paths:
      - "qis-compiler/pyproject.toml"
      - ".github/workflows/python-qis-wheels.yml"
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

env:
  CARGO_TERM_COLOR: always
  UV_VERSION: "0.11.15"
jobs:
  # Check if the tag matches the package name,
  # or if the workflow is running on a non-tag event.
  check-tag:
    name: Check tag
    runs-on: ubuntu-latest
    outputs:
      run: ${{ steps.check-tag.outputs.run }}
    steps:
      - name: Check tag
        id: check-tag
        run: |
          echo "run=$SHOULD_RUN" >> $GITHUB_OUTPUT
        env:
          SHOULD_RUN: ${{ github.ref_type != 'tag' || startsWith(github.ref, 'refs/tags/qis-compiler-v') }}

  build_qis_compiler_wheels:
    needs: check-tag
    if: ${{ needs.check-tag.outputs.run == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - macos-15
          - macos-15-intel
          - windows-2022
    name: "qis-compiler wheels (${{matrix.os}})"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - name: Set up UV
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          version: ${{ env.UV_VERSION }}

      - uses: quantinuum/hugrverse-env/install-hugrenv-action@main

      - name: Build selene-hugr-qis-compiler wheel
        uses: pypa/cibuildwheel@v3.4.1
        with:
          package-dir: qis-compiler

      - name: Check built wheels
        run: uvx twine check --strict wheelhouse/*.whl

      - name: Upload wheels
        uses: actions/upload-artifact@v7
        with:
          name: qis-compiler-wheels-${{ matrix.os }}
          path: wheelhouse/*.whl
          if-no-files-found: error

  release:
    name: Release qis-compiler
    needs: [check-tag, build_qis_compiler_wheels]
    if: ${{ needs.check-tag.outputs.run == 'true' && github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/qis-compiler-v') }}
    runs-on: ubuntu-latest
    # always do a full build and test before release of any package
    environment: release
    permissions:
      contents: write
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
      # Used to generate artifact attestation
      attestations: write
    steps:
      - name: Check if the tag has an associated release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release view ${{ github.ref_name }}
          if [ $? -ne 0 ]; then
            echo "No release found for tag ${{ github.ref_name }}"
            exit 1
          fi
      - uses: actions/download-artifact@v8
        with:
          path: wheelhouse
          merge-multiple: true
      - name: Generate artifact attestation
        uses: actions/attest@v4
        with:
          subject-path: "wheelhouse/*"

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          skip-existing: true
          packages-dir: wheelhouse

      - name: Upload wheels to the release and un-draft it
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Upload wheels to the release assets
          gh release upload ${{ github.ref_name }} wheelhouse/*
          # Un-draft the release on GitHub now that the package has been published to PyPI
          gh release edit ${{ github.ref_name }} --draft=false
