name: Rust Semver Checks
on:
  pull_request:
    branches:
      - main

jobs:
  # Check if changes were made to the relevant files.
  # Always returns true if running on the default branch, to ensure all changes are thoroughly checked.
  changes:
    name: Check for changes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      rust: ${{ steps.filter.outputs.rust }}
      python: ${{ steps.filter.outputs.python }}
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/check-changes
        id: filter

  rs-semver-checks:
    needs: [changes]
    if: ${{ needs.changes.outputs.rust == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tket
        uses: actions/checkout@v6
      - name: Install conan
        uses: conan-io/setup-conan@v1
        with:
          cache_packages: true
      - name: Install LLVM from apt
        run: |
          echo "Installing apt dependencies: llvm-14"
          sudo apt-get install -y llvm-14
      - uses: quantinuum/hugrverse-actions/rs-semver-checks@main
        with:
          token: ${{ secrets.HUGRBOT_PAT }}
