name: Unsoundness checks

on:
  schedule:
    # Weekly on Monday at 04:00 UTC
    - cron: "0 4 * * 1"
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "--cfg=ci_run"
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  # Permissive provenance is required due to warnings in bitvec 1.0.1
  # Proptest flags required to fix https://github.com/proptest-rs/proptest/issues/253
  MIRIFLAGS: "-Zmiri-permissive-provenance -Zmiri-env-forward=PROPTEST_DISABLE_FAILURE_PERSISTENCE"
  PROPTEST_DISABLE_FAILURE_PERSISTENCE: true

  # different strings for install action and feature name
  # adapted from https://github.com/TheDan64/inkwell/blob/master/.github/workflows/test.yml
  LLVM_MAIN_VERSION: "21"
  LLVM_VERSION: "21.1"
  LLVM_FEATURE_NAME: "21-1"

  # Path to the cached tket-c-api library
  # When this envvar is set, the `./.github/actions/tket-c-api` action **must** be run to fetch the artifacts
  # This config is not required, but speeds up the build by caching the tket-c-api library
  # The alternative is to install conan and remove the env var
  TKET_C_API_PATH: "${{ github.workspace }}/tket-c-api"
  LD_LIBRARY_PATH: ${{ github.workspace }}/tket-c-api/lib

jobs:
  miri:
    name: "Miri"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: mozilla-actions/sccache-action@v0.0.9
      - name: Install Miri
        run: |
          rustup toolchain install nightly --component miri
          rustup override set nightly
          cargo miri setup
      - name: Install LLVM and Clang
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository 'deb http://apt.llvm.org/noble/   llvm-toolchain-noble-${{ env.LLVM_MAIN_VERSION }}  main'
          sudo apt update
          sudo apt install llvm-${{ env.LLVM_MAIN_VERSION }} libpolly-${{ env.LLVM_MAIN_VERSION }}-dev
      - name: Install tket-c-api library
        uses: ./.github/actions/tket-c-api
        with:
          install-path: ${{ env.TKET_C_API_PATH }}

      # Run miri unsoundness checks.
      #
      # Skip tests that take over 5mins in CI.
      - name: Test with Miri
        run: |
          cargo miri nextest run --no-default-features -- \
            `# -------- tket::passes` \
            --skip "dataflow::partial_value::test::bounded_lattice" \
            --skip "dataflow::partial_value::test::lattice" \
            --skip "dataflow::partial_value::test::lattice_associative" \
            --skip "dataflow::partial_value::test::meet_join_self_noop" \
            --skip "dataflow::partial_value::test::partial_value_type" \
            --skip "dataflow::partial_value::test::partial_value_valid" \
            --skip "merge_bbs::test::check_ext_id_wellformed" \
            --skip "monomorphize::test::test_recursion_module" \
            --skip "normalize_cfgs::test::check_ext_id_wellformed" \
            --skip "replace_types::test::dfg_conditional_case" \
            --skip "replace_types::test::module_func_cfg_call" \
            --skip "replace_types::test::op_to_call" \
            #

  create-issue:
    uses: quantinuum/hugrverse-actions/.github/workflows/create-issue.yml@main
    needs: miri
    if: always() && needs.miri.result == 'failure' && github.ref == 'refs/heads/main'
    secrets:
      GITHUB_PAT: ${{ secrets.HUGRBOT_PAT }}
    with:
      title: "💥 Unsoundness check fail on main"
      body: |
        The unsoundness check for `quantinuum/tket2` failed.

        [Please investigate](https://github.com/quantinuum/tket2/actions/runs/${{ github.run_id }}).
      unique-label: "X-unsoundness-checks"
      other-labels: "C-bugfix"
