name: Unsoundness checks

on:
  schedule:
    # Weekly on Monday at 04:00 UTC
    - cron: "0 4 * * 1"
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "--cfg=ci_run"
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  # Permissive provenance is required due to warnings in bitvec 1.0.1
  # Proptest flags required to fix https://github.com/proptest-rs/proptest/issues/253
  MIRIFLAGS: "-Zmiri-permissive-provenance -Zmiri-env-forward=PROPTEST_DISABLE_FAILURE_PERSISTENCE"
  PROPTEST_DISABLE_FAILURE_PERSISTENCE: true

  HUGRENV_VERSION: "0.3.1"
  HUGRENV_ROOT: "/tmp/hugrverse"
  HUGRENV_PLATFORM: "manylinux_2_28_x86_64"
  TKET_C_API_PATH: "/tmp/hugrverse"
  LD_LIBRARY_PATH: "/tmp/hugrverse/lib:/tmp/hugrverse/lib64"
  LLVM_SYS_211_PREFIX: "/tmp/hugrverse"

jobs:
  miri:
    name: "Miri"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: mozilla-actions/sccache-action@v0.0.10
      - name: Install Miri
        run: |
          rustup toolchain install nightly --component miri
          rustup override set nightly
          cargo miri setup
      - uses: quantinuum/hugrverse-env/install-hugrenv-action@main
      - name: Install nextest
        uses: taiki-e/install-action@nextest

      # Run miri unsoundness checks.
      #
      # Skip tests that take over 60s in CI.
      - name: Test with Miri
        run: |
          cargo miri nextest run --no-default-features --no-fail-fast -- \
            `# -------- tket::modifier` \
            --skip "modifier::modifier_resolver::call_modify::tests::test_call_modify" \
            --skip "modifier::modifier_resolver::dfg_modify::test::test_dfg_modify" \
            --skip "modifier::modifier_resolver::global_phase_modify::tests::test_global_phase_modify" \
            `# -------- tket::passes` \
            --skip "dataflow::partial_value::test::bounded_lattice" \
            --skip "dataflow::partial_value::test::lattice" \
            --skip "dataflow::partial_value::test::lattice_associative" \
            --skip "dataflow::partial_value::test::meet_join_self_noop" \
            --skip "dataflow::partial_value::test::partial_value_type" \
            --skip "dataflow::partial_value::test::partial_value_valid" \
            --skip "merge_bbs::test::check_ext_id_wellformed" \
            --skip "monomorphize::test::test_recursion_module" \
            --skip "normalize_cfgs::test::check_ext_id_wellformed" \
            --skip "replace_types::linearize::test::sum_nway_copy" \
            --skip "replace_types::linearize::test::test_copy_borrow_array" \
            --skip "replace_types::linearize::test::use_in_op_callback" \
            --skip "replace_types::test::compositionality" \
            --skip "replace_types::test::dfg_conditional_case" \
            --skip "replace_types::test::module_func_cfg_call" \
            --skip "replace_types::test::op_to_call" \
            --skip "replace_types::test::regions" \
            --skip "serialize::pytket::tests::circuit_standalone_roundtrip" \
            --skip "serialize::tests::func_circuit_store" \
            --skip "serialize::tests::root_circuit_store" \
            --skip "serialize::tests::serialize_package_errors" \
            `# -------- tket_qsystem` \
            --skip "extension::qsystem::barrier::test::test_barrier" \
            --skip "extension::qsystem::lower::test::test_array_clone_discard_measurement" \
            --skip "extension::qsystem::lower::test::test_barray_get_measurement" \
            --skip "extension::qsystem::lower::test::test_mixed" \
            --skip "test::no_public_funcs" \
            #

  create-issue:
    uses: quantinuum/hugrverse-actions/.github/workflows/create-issue.yml@main
    needs: miri
    if: always() && needs.miri.result == 'failure' && github.ref == 'refs/heads/main'
    secrets:
      GITHUB_PAT: ${{ secrets.HUGRBOT_PAT }}
    with:
      title: "💥 Unsoundness check fail on main"
      body: |
        The unsoundness check for `quantinuum/tket2` failed.

        [Please investigate](https://github.com/quantinuum/tket2/actions/runs/${{ github.run_id }}).
      unique-label: "X-unsoundness-checks"
      other-labels: "C-bugfix"
